//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_vrproep : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Vector2 Trackpad
        {
            get
            {
                return SteamVR_Actions.vrproep_Trackpad;
            }
        }
        
        public virtual SteamVR_Action_Boolean InterfaceEnableButton
        {
            get
            {
                return SteamVR_Actions.vrproep_InterfaceEnableButton;
            }
        }
        
        public virtual SteamVR_Action_Boolean ObjectInteractButton
        {
            get
            {
                return SteamVR_Actions.vrproep_ObjectInteractButton;
            }
        }
        
        public virtual SteamVR_Action_Pose ResidualLimbPose
        {
            get
            {
                return SteamVR_Actions.vrproep_ResidualLimbPose;
            }
        }
        
        public virtual SteamVR_Action_Pose ForearmPose
        {
            get
            {
                return SteamVR_Actions.vrproep_ForearmPose;
            }
        }
        
        public virtual SteamVR_Action_Pose ShoulderPose
        {
            get
            {
                return SteamVR_Actions.vrproep_ShoulderPose;
            }
        }
        
        public virtual SteamVR_Action_Pose C7Pose
        {
            get
            {
                return SteamVR_Actions.vrproep_C7Pose;
            }
        }
        
        public virtual SteamVR_Action_Pose MRCameraPose
        {
            get
            {
                return SteamVR_Actions.vrproep_MRCameraPose;
            }
        }
        
        public virtual SteamVR_Action_Pose HandPose
        {
            get
            {
                return SteamVR_Actions.vrproep_HandPose;
            }
        }
        
        public virtual SteamVR_Action_Vibration HapticFeedback
        {
            get
            {
                return SteamVR_Actions.vrproep_HapticFeedback;
            }
        }
    }
}
